Script for create db
Network-Assignment-Team-NAT/database pull request #2
Opened 2024-01-15 06:56 UTC by alpdk

I added script for creating our database and tables that we need. Please check, that all needed table and types of columns are correct.

2024-01-15 07:57 UTC, alpdk commented
I have an idea to add default values for:
1) end of traffic date
2) end of traffic time

I think that it can be useful, but I am not sure.

2024-01-15 17:23 UTC, InnocentusLime commented on create_db.script
> +psql -U postgres -d nat_database -c 'ALTER TABLE traffic ADD COLUMN who_spend_it TEXT NOT NULL;'
You can just feed sql command file into the database instead of doing this monstrocity:

```bash
psql -U postgres -f sql_commands
```

See [the documentation](https://linux.die.net/man/1/psql). Also can be viewed with `man psql`

2024-01-15 17:24 UTC, InnocentusLime requested changes
Please fix this

2024-01-25 06:25 UTC, InnocentusLime commented
Merge conflict with the main branch. Cannot merge

2024-01-25 14:10 UTC, merged