Scripts for working with db
Network-Assignment-Team-NAT/database pull request #3
Opened 2024-01-15 11:10 UTC by alpdk

There you can find some scripts for working with scripts, check them please.

2024-01-15 17:19 UTC, InnocentusLime commented on traffic_info.sh
Looks like `create_traffic.sh` would be a better name

2024-01-15 17:20 UTC, InnocentusLime requested changes
Looks good. Just rename one script :)

2024-01-16 12:44 UTC, alpdk commented on traffic_info.sh
I am not sure, because we are not creating traffic we are making logs for traffic that people use.

2024-01-25 06:23 UTC, InnocentusLime approved these changes
Excellent. Merging.

2024-01-25 06:23 UTC, merged